### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by tobias-g1** [evanmarshall/steemit-cloud#1]
Can you add a license so we can contribute via utopian please

Snippet from utopian rules:
![image](https://user-images.githubusercontent.com/17148879/36640967-42f8099c-1a20-11e8-946e-00e078a0a374.png)

**Comment by evanmarshall** [comment]
Definitely. Added here: https://github.com/evanmarshall/steemit-cloud/commit/e24dd03ea156dee5f76c449672ffd3c9888950b4
